[env]
_.file = '.env'

[tools]
aws = "2.31.13"
node = "24.10.0"
pnpm = "10.18.2"
uv = "0.9.2"

[tasks.dev]
description = "Start the SST development server"
run = "pnpm sst:dev"

[tasks."dev-remove"]
description = "Remove the SST development server"
run = "pnpm dev-remove"

[tasks.deploy]
description = "Deploy the SST production server"
run = "pnpm prod-deploy"

[tasks.remove]
description = "Remove the SST production server"
run = "pnpm prod-remove"

[tasks."pre-commit"]
description = "Execute before commit"
run = """
pnpm check
"""

[hooks]
postinstall = """
pnpm install
mise generate git-pre-commit --write --task=pre-commit
"""
