[project]
name = "agentcore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bedrock-agentcore>=0.1.7",
    "bedrock-agentcore-starter-toolkit>=0.1.21",
    "pydantic>=2.12.0",
    "ruff>=0.14.0",
    "strands-agents>=1.12.0",
    "strands-agents-tools>=0.2.12",
]
